// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package graph

import (
	"github.com/heyjun3/notify-stock/internal"
	"github.com/uptrace/bun"
	"log/slog"
)

// Injectors from wire.go:

func InitResolver(db *bun.DB, logger *slog.Logger) *Resolver {
	stockRepository := notifystock.InitStockRepository(db)
	symbolRepository := notifystock.InitSymbolRepository(db)
	notificationRepository := notifystock.InitNotificationRepository(db)
	notificationCreator := notifystock.InitNotificationCreator(db)
	dataLoader := notifystock.NewDataLoader(symbolRepository)
	resolver := NewResolver(stockRepository, symbolRepository, notificationRepository, notificationCreator, dataLoader, logger)
	return resolver
}

func InitRootDirective(logger *slog.Logger) *DirectiveRoot {
	directive := NewAuthDirective(logger)
	directiveRoot := NewDirectiveRoot(directive)
	return directiveRoot
}
